
  CREATE TABLE "HR"."TB_SAMPLE_FOOD_ORDER_ITEMS" 
   (	"ORDER_NO" NUMBER(5,0), 
	"FOOD_NO" NUMBER(4,0), 
	"FOOD_AMOUNT" NUMBER(2,0), 
	 CONSTRAINT "ITEM_AMOUNT_CK" CHECK (FOOD_AMOUNT > 0) ENABLE, 
	 CONSTRAINT "ITEM_ORDERNO_FK" FOREIGN KEY ("ORDER_NO")
	  REFERENCES "HR"."TB_SAMPLE_FOOD_ORDERS" ("ORDER_NO") ENABLE, 
	 CONSTRAINT "ITEM_FOODNO_FK" FOREIGN KEY ("FOOD_NO")
	  REFERENCES "HR"."TB_SAMPLE_FOODS" ("FOOD_NO") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

