
  CREATE TABLE "HR"."TB_SAMPLE_FOOD_ORDERS" 
   (	"ORDER_NO" NUMBER(7,0), 
	"CUSTOMER_NO" NUMBER(4,0), 
	"ORDER_TOTAL_PRICE" NUMBER(7,0), 
	"ORDER_STATUS" VARCHAR2(30 BYTE) DEFAULT '주문완료', 
	"ORDER_CREATED_DATE" DATE DEFAULT SYSDATE, 
	 CONSTRAINT "FOODORDER_PRICE_CK" CHECK (ORDER_TOTAL_PRICE > 0) ENABLE, 
	 CONSTRAINT "FOODORDER_NO_PK" PRIMARY KEY ("ORDER_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FOODORDER_CUSTNO_FK" FOREIGN KEY ("CUSTOMER_NO")
	  REFERENCES "HR"."TB_SAMPLE_FOOD_CUSTOMERS" ("CUSTOMER_NO") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

