
  CREATE TABLE "HR"."TB_SAMPLE_FOODS" 
   (	"FOOD_NO" NUMBER(4,0), 
	"FOOD_NAME" VARCHAR2(200 BYTE) CONSTRAINT "FOOD_NAME_NN" NOT NULL ENABLE, 
	"FOOD_PRICE" NUMBER(7,0), 
	"FOOD_STOCK" NUMBER(4,0), 
	"FOOD_ON_SALE" VARCHAR2(30 BYTE) DEFAULT '∆«∏≈¡ﬂ', 
	"CATEGORY_NO" NUMBER(4,0), 
	 CONSTRAINT "FOOD_NO_PK" PRIMARY KEY ("FOOD_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FOOD_CATNO_FK" FOREIGN KEY ("CATEGORY_NO")
	  REFERENCES "HR"."TB_SAMPLE_FOOD_CATEGORIES" ("CATEGORY_NO") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE INDEX "HR"."FOOD_NAME_IDX" ON "HR"."TB_SAMPLE_FOODS" ("FOOD_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

